updated vignette to reflect Moonlight2 in greater detail
ELELAB/Moonlight2R pull request #28
Opened 2022-12-01 10:33 UTC by mona-n

fixes #26

2022-12-06 16:00 UTC, mtiberti requested changes
one additional point

- this sentence is unfinished: For methylation data, DPA is running a differentially methylated regions analysis (DMR) to identify differentially methylated CpG sites using the TCGAanalyze_DMR the TCGAanalyze_DMR function from .

2022-12-12 09:41 UTC, mona-n commented on vignettes/Moonlight2R.Rmd
> +3. **FEA** Functional Enrichment Analysis (EA), using Fisher's test, to identify gene sets (with biological functions linked to cancer) significantly enriched by RG.
updated:
removed FEA abbreviation for consistency in text as abbreviations are not mentioned in the other places
defined RG acronym

2022-12-12 09:41 UTC, mona-n commented on vignettes/Moonlight2R.Rmd
>  2. **DPA** Differential Phenotype Analysis (DEA) to identify genes or probes that are different significantly with two phenotypes such as normal and tumor, or normal and stageI, normal and molecular
updated:
removed DEA abbreviation for consistency with the rest of the text
updated "are different significantly" to "are significantly different"

2022-12-12 09:41 UTC, mona-n commented on vignettes/Moonlight2R.Rmd
> +In 2020, we developed the Moonlight framework that allows for prediction of cancer driver genes (Colaprico and Olsen et al., 2020). Here, gene expression data are integrated together with biological
updated both

2022-12-12 09:41 UTC, mona-n commented on vignettes/Moonlight2R.Rmd
> +To install Moonlight2R use the code below.
updated

2022-12-12 09:42 UTC, mona-n commented on vignettes/Moonlight2R.Rmd
>  ## Citation
updated:
citation section moved to the end before bibliography

I'm not sure how to get a full citation automatically and which part this refers to?

2022-12-12 09:43 UTC, mona-n commented on vignettes/Moonlight2R.Rmd
>  devtools::install_github(repo = "ELELAB/Moonlight2R")
updated

2022-12-12 09:43 UTC, mona-n commented on vignettes/Moonlight2R.Rmd
> +if (!require("BiocManager", quietly = TRUE))
updated all

2022-12-12 09:43 UTC, mona-n commented on vignettes/Moonlight2R.Rmd
> +This function will further generate three files: DEG_Mutations_Annotations.rda, Oncogenic_mediators_mutation_summary.rda and cscape_somatic_output.rda. These will be placed in the specified results-f
updated

2022-12-15 16:17 UTC, merged